#!/bin/bash

TMP_DIR="/tmp/blackbox_tmporary/"
ARCHIVE_DISK="/media/""$(whoami)""/BLACKBOX"
ARCHIVE_DIR="/var/tmp/blackbox_archive"
ARCHIVE_COUNT=51

if [ -d "$ARCHIVE_DISK" ]; then
    ARCHIVE_DIR="$ARCHIVE_DISK""/blackbox_archive"
    ARCHIVE_COUNT=512
fi


if [ -d "$TMP_DIR" ]; then
    mkdir -m 777 -p $ARCHIVE_DIR
    # TMP_DIRR内の全てのファイルおよびディレクトリをループ処理
    for entry in "$TMP_DIR"*
    do
        filename=$(basename "$entry")

        if [ -n "$1" ]; then
            if [ "$entry" == "$1" ]; then
                continue
            fi
        fi

        mv "$entry" "$ARCHIVE_DIR"
        echo "Moving $entry to $ARCHIVE_DIR"
    done

    DELETE_ARCHIVE=$(cd $ARCHIVE_DIR && ls -tA1 . | tail -n+$ARCHIVE_COUNT)
    (cd $ARCHIVE_DIR && rm -rf $DELETE_ARCHIVE)
    echo "Delete archive : $DELETE_ARCHIVE"
fi
